import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const SITE_TITLE = "Generated by Midjourney";
const SITE_DESCRIPTION =
  "hanetsukiがMidjourneyで生成したイラストを集めたサイトです";
const SITE_URL =
  process.env.NODE_ENV === "development"
    ? "http://localhost:3000"
    : "https://midjourney.tsuki-lab.net/";

export const metadata: Metadata = {
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    type: "website",
    url: SITE_URL,
  },
  twitter: {
    card: "summary",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    creator: "@hanetsuki_dev",
  },
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <h1 className="text-center text-xl mb-8 mt-4">
          <Link href="/">Generated by Midjourney</Link>
        </h1>
        {children}
        {modal}
      </body>
    </html>
  );
}
