import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Generated by Midjourney",
  description: "hanetsukiがMidjourneyで生成したイラストを集めたサイトです",
  alternates: {
    canonical:
      process.env.NODE_ENV === "development"
        ? "http://localhost:3000"
        : "https://midjourney.tsuki-lab.net/",
  },
  openGraph: {
    title: "Generated by Midjourney",
    description: "hanetsukiがMidjourneyで生成したイラストを集めたサイトです",
    type: "website",
    url:
      process.env.NODE_ENV === "development"
        ? "http://localhost:3000"
        : "https://midjourney.tsuki-lab.net/",
  },
  twitter: {
    card: "summary",
    title: "Generated by Midjourney",
    description: "hanetsukiがMidjourneyで生成したイラストを集めたサイトです",
    creator: "@hanetsuki_dev",
  },
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <h1 className="text-center text-xl mb-8 mt-4">
          <Link href="/">Generated by Midjourney</Link>
        </h1>
        {children}
        {modal}
      </body>
    </html>
  );
}
